name: Docker Ubuntu Desktop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 305  # slightly longer than 300 minutes to accommodate startup time

    services:
      xrdp:
        image: dorowu/ubuntu-desktop-lxde-vnc
        options: --privileged --shm-size=2g -p 3389:3389 -p 2222:22  # Expose RDP on port 3389 and SSH on port 2222

    container:
      image: dorowu/ubuntu-desktop-lxde-vnc
      options: --privileged --shm-size=2g -p 3389:3389 -p 2222:22  # Ensure ports are exposed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build . -t my-ubuntu-desktop

      - name: Run the Docker container
        run: |
          docker run -d --name ubuntu-desktop \
            --privileged \
            --shm-size=2g \
            -p 3389:3389 \
            -p 2222:22 \
            my-ubuntu-desktop

      - name: Wait for services to be ready
        run: sleep 30  # Adjust based on container startup time

      - name: Display container logs
        run: docker logs ubuntu-desktop

      - name: Run tests (replace with actual tests)
        run: echo "Running tests..."

      - name: Stop the Docker container
        run: docker stop ubuntu-desktop
